name: etruscan
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.11  
  - numpy
  - matplotlib
  - pandas
  - jupyter
  - jupyterlab
  - nltk
  - tqdm
  - black
  - tabulate
  - seaborn
  - ipython
  - levenshtein
  - cuda-nvcc
  - jax
  - jaxlib=*=*cuda*  
  - sacrebleu
  - sentencepiece
  - optax  
  - datasets
  - pip:
    - flax=0.6.8 # TODO wait for conda. checkpoints do not work with 0.6.1
    - tensorflow=2.12 # TODO wait for conda, no need for cuda support
    - orbax-checkpoint # flax.training.checkpoints not working, use orbax instead
    - clu
    - gcld3
    - pymupdf

# APT:
#  - protobuf-compiler
